artifacts_root: artifacts

reader_config: 
  file_path: ./data/
  
milvus_config: 
  host: localhost
  port: 19530
  address: null
  uri: null
  user: null
  embedding_field: embedding
  primary_field: id
  text_field: null
  consistency_level: null
