artifacts_root: artifacts

file_data_path: data/
language: vi

use_async: False
show_progress: False

vector_store_query_mode: default
store_nodes_override: False
insert_batch_size: 4096
similarity_top_k: 10

defaults:
  - embedding: cross
  - splitter: sentence
  - vector_store: milvus
  - rerank: asymmetric