MilvusParams:
  collection_name: MilvusCollection
  embedding_dim: 384
  overwrite: True
  search_params: 
    metric_type: COSINE
    offset: 0
    ignore_growing: False
    params: 
      nprobe: 10
  index_params: 
    metric_type: COSINE
    index_type: IVF_FLAT
    params: 
      nlist: 1024


embeddings_params:
  model_name: BAAI/bge-small-en
  tokenizer_name: BAAI/bge-small-en
  pooling: cls
  max_length: 512
  normalize: True
  embedding_batch_size: 10
  cache_folder: ./
  trust_remote_code: True


IndexRetrieveParams:
  index_type: vector_store
  similarity_top_k: 2
  sparse_top_k: null 
  alpha: null
  list_query_mode: null
  keyword_table_mode: null
  max_keywords_per_chunk: null
  max_keywords_per_query: null
  num_chunks_per_query: null
  vector_store_query_mode: default
  store_nodes_override: False
  insert_batch_size: 2048
  use_async: False
  show_progress: False

NodeParserParams:
  model_name_tokenizer: BAAI/bge-small-en
  # fpr sentence splitter 
  splitter_mode: sentence
  separator: " "
  chunk_size: 256
  chunk_overlap: 20
  paragraph_separator: \n\n\n
  secondary_chunking_regex: "[^,.;。？！]+[,.;。？！]?"
  # for token splitter
  backup_separators: null
