MilvusParams:
  collection_name: LangChainCollection
  consistency_level: Session
  index_params: null
  search_params: null
  overwrite: False
  primary_field: doc_id
  text_field: text
  vector_field: embedding
  similarity_metric: ip